### ISSUE TITLE
NameError: global name 'cache' is not defined

### ISSUE THREAD

**Issue by Shatnerz** [robertchase/rhc#10]
Traceback (most recent call last):
      File "play/add_equifax.py", line 122, in <module>
        main()
      File "play/add_equifax.py", line 115, in main
        update_sbfe(app_id, sbfe_json)
      File "play/add_equifax.py", line 76, in update_sbfe
        Sbfe.process_report(sbfe, app_id)
      File "/opt/data/git/vesuvius/vesuvius/logic/sbfe.py", line 71, in process_report
        sbfe.save()
      File "/opt/data/git/rhc/rhc/database/dao.py", line 209, in save
        self._save(insert)
      File "/opt/data/git/rhc/rhc/database/dao.py", line 240, in _save
        setattr(self, n, cache[n])
    NameError: global name 'cache' is not defined

**Comment by robertchase** [comment]
moved exception handling up a layer and added cleanup in finally block.

fixed with: 2765f55fcff85768dd6c75c821ba35e8b1701e5e
